### ISSUE TITLE
Windows 10 .url and office

### ISSUE THREAD

**Issue by tnmeesters** [GChristensen/enso-portable#24]
Hello,

I have an issue with enso opening websites/url files. Instead of opening the default browser it opens up the install directory of enso C:\Users\....\AppData\Roaming\Enso.

and

Enso also does not open my Microsoft office programs located in C:\Program Files\Microsoft Office\root\Office16. I do not understand why this is. All other programs open just fine.

I'm running windows 10 64 and use edge as browser.

Love this program can not do without it.

Thank you,

Thomas

**Comment by GChristensen** [comment]
Hi, 

There was a bug in opening .url shortcuts, and it should be fixed in v.0.6.1.

Some programs may not open because an invalid path is specified in the program shortcut at the start menu. For example, It may contain "Program files (x64)" while the program is actually located at "Program files". Windows start menu somehow automatically deals with such errors, but shell API used by Enso could not do this. The only way to check the correctness of the shortcut path is through the properties of shortcuts, where it also possible to correct it. Office shortcuts are usually located directly at C:\Users\All Users\Start Menu\Programs\. If shortcut paths seems correct, another workaround is to delete these shortcuts and create new ones through "learn as open" enso command for the programs at C:\Program Files\Microsoft Office\root\Office16.
