### ISSUE TITLE
enso ot triggering when administrator app has focus

### ISSUE THREAD

**Issue by mawiseman** [GChristensen/enso-portable#25]
If i have an instance of powershell open running in administrator mode, then hit caps to launch enso it is not triggered.

If i run enso in admin mode it works... but then every time i boot my computer UAC prompts me to allow it.
I can't turn UAC off due to work restrictions

Other launchers like keypirinha don't seem to have this issue.

**Comment by GChristensen** [comment]
This is a fundamental Enso issue since it was developed as a modeless application before UAC was in widespread use. It uses hooks to get input (it has no its own input window as other launchers), and it is impossible (or very non-trivial) to hook into elevated processes from non-elevated ones, so nothing could be done about this, unfortunately.

**Comment by mawiseman** [comment]
Thanks. Reading this I feel like I raised it before... Sorry
